"""Constants for SolarTouch LAN."""

DOMAIN = "solarmax_touch_lan"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_SLAVE = "slave"
CONF_CONNECTION_MODE = "connection_mode"
CONF_DAILY_CLOUD_SYNC = "daily_cloud_sync"
CONF_PERIODIC_INTERVAL = "periodic_interval"

CONNECTION_MODE_STANDBY = "standby"
CONNECTION_MODE_PERIODIC = "periodic"
CONNECTION_MODE_LIVE = "live"
CONNECTION_MODE_ALWAYS_ON = CONNECTION_MODE_LIVE  # legacy alias

PERIODIC_INTERVAL_DEFAULT = 5  # minutes

LIVE_SESSION_SECONDS = 300       # 5 minutes
WRITE_LINGER_SECONDS = 60        # 1 minute after a write
CLOUD_SYNC_PAUSE_SECONDS = 360   # 6 minutes at 23:45
CLOUD_SYNC_HOUR = 23
CLOUD_SYNC_MINUTE = 45

SCAN_FAST_SECONDS = 10        # live mode poll interval
SCAN_LIVE_FAST_SECONDS = 5    # during a Go Live session
SCAN_SLOW_SECONDS = 60

SLAVE_DEFAULT = 1
PORT_DEFAULT = 502

# ── Sensor definitions ────────────────────────────────────────────────────────
# (name, unique_id, register, data_type, scale, unit, device_class, state_class,
#  swap_words, fast)
#
# data_type: "uint16" | "uint32" | "int16" | "int32"
# swap_words: True → read two registers and swap word order before combining

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

SENSOR_DEFINITIONS = [
    # ── FAST sensors (30 s) ───────────────────────────────────────────────────
    {
        "name": "11. Live PV Total Power",
        "key": "live_pv_total_power",
        "register": 4168,
        "data_type": "uint32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "12. PV1 Voltage",
        "key": "pv1_voltage",
        "register": 4112,
        "data_type": "uint16",
        "scale": 0.1,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "13. PV1 Current",
        "key": "pv1_current",
        "register": 4113,
        "data_type": "uint16",
        "scale": 0.01,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "14. PV1 Power",
        "key": "pv1_power",
        "register": 4114,
        "data_type": "uint32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "15. PV2 Voltage",
        "key": "pv2_voltage",
        "register": 4116,
        "data_type": "uint16",
        "scale": 0.1,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "16. PV2 Current",
        "key": "pv2_current",
        "register": 4117,
        "data_type": "uint16",
        "scale": 0.01,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "17. PV2 Power",
        "key": "pv2_power",
        "register": 4118,
        "data_type": "uint32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "18. PV3 Voltage",
        "key": "pv3_voltage",
        "register": 4120,
        "data_type": "uint16",
        "scale": 0.1,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "19. PV3 Current",
        "key": "pv3_current",
        "register": 4121,
        "data_type": "uint16",
        "scale": 0.01,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "20. PV3 Power",
        "key": "pv3_power",
        "register": 4122,
        "data_type": "uint32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "21. Battery Power",
        "key": "battery_power",
        "register": 8201,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "22. Battery State of Charge",
        "key": "battery_soc",
        "register": 8192,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "38. Load Power",
        "key": "load_power",
        "register": 4875,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": True,
        "fast": True,
    },
    {
        "name": "30. Grid Power",
        "key": "grid_power",
        "register": 4865,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": True,
        "fast": True,
    },
    {
        "name": "32. Inverter CT Clamp Power",
        "key": "inverter_ct_clamp_power",
        "register": 4864,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    {
        "name": "41. Light Load Power",
        "key": "light_load_power",
        "register": 4947,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": True,
    },
    # ── SLOW sensors (5 min) ──────────────────────────────────────────────────
    {
        "name": "25. Battery Temperature",
        "key": "battery_temperature",
        "register": 8220,
        "data_type": "int16",
        "scale": 1,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "23. Battery Voltage",
        "key": "battery_voltage",
        "register": 8198,
        "data_type": "uint16",
        "scale": 0.1,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "24. Battery Current",
        "key": "battery_current",
        "register": 8200,
        "data_type": "int32",
        "scale": 0.01,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": True,
        "fast": False,
    },
    {
        "name": "26. Today Battery Energy Charge",
        "key": "battery_charge_energy_today",
        "register": 8203,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "swap": False,
        "fast": False,
    },
    {
        "name": "27. Battery Charge Lifetime Energy",
        "key": "battery_charge_lifetime_energy",
        "register": 8205,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": False,
        "fast": False,
    },
    {
        "name": "28. Battery Discharge Energy Today",
        "key": "battery_discharge_energy_today",
        "register": 8207,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "swap": False,
        "fast": False,
    },
    {
        "name": "29. Battery Discharge Lifetime Energy",
        "key": "battery_discharge_lifetime_energy",
        "register": 8209,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": False,
        "fast": False,
    },
    {
        "name": "08. Discharge End SOC (on battery)",
        "key": "discharge_end_soc_on_battery",
        "register": 8475,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "07. Discharge End SOC (on grid)",
        "key": "discharge_end_soc_on_grid",
        "register": 8522,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "Off-Grid Mode",
        "key": "off_grid_mode",
        "register": 8476,
        "data_type": "uint16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "swap": False,
        "fast": False,
    },
    {
        "name": "05. Max Grid Charging Power",
        "key": "maximum_grid_charging_power",
        "register": 8470,
        "data_type": "uint16",
        "scale": 1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "02. Max Grid Export Power",
        "key": "max_grid_export_power",
        "register": 12473,
        "data_type": "uint32",
        "scale": 1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "06. Stop Grid Charging Battery SOC",
        "key": "stop_grid_charging_battery_soc",
        "register": 8471,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "03. Battery Charging Max Power",
        "key": "battery_charging_max_power",
        "register": 8472,
        "data_type": "uint16",
        "scale": 1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "04. Battery Stop Charging Maximum SOC",
        "key": "battery_stop_charging_maximum_soc",
        "register": 8473,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "33. Grid Frequency",
        "key": "grid_frequency",
        "register": 4920,
        "data_type": "uint16",
        "scale": 0.01,
        "unit": "Hz",
        "device_class": SensorDeviceClass.FREQUENCY,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "49. Smart Load Power",
        "key": "smart_load_power",
        "register": 4974,
        "data_type": "int16",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "09. Smart Load Turn ON Battery SOC",
        "key": "smart_load_turn_on_battery_soc",
        "register": 8492,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "10. Smart Load Turn OFF Battery SOC",
        "key": "smart_load_turn_off_battery_soc",
        "register": 8493,
        "data_type": "uint16",
        "scale": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "47. Inverter Internal Temperature",
        "key": "inverter_internal_temperature",
        "register": 4124,
        "data_type": "int16",
        "scale": 1,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "43. Energy Produced Today",
        "key": "energy_produced_today",
        "register": 4135,
        "data_type": "uint32",
        "scale": 0.001,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "swap": False,
        "fast": False,
    },
    {
        "name": "44. Energy Produced Lifetime",
        "key": "energy_produced_lifetime",
        "register": 4130,
        "data_type": "uint32",
        "scale": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": True,
        "fast": False,
    },
    {
        "name": "48. Inverter Operating Hours",
        "key": "inverter_operating_hours",
        "register": 4132,
        "data_type": "uint32",
        "scale": 1,
        "unit": "h",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": True,
        "fast": False,
    },
    {
        "name": "45. Peak Production Power Today",
        "key": "peak_production_power_today",
        "register": 4155,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "35. Energy Import Lifetime",
        "key": "energy_import_lifetime",
        "register": 4870,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": False,
        "fast": False,
    },
    {
        "name": "34. Energy Import Today",
        "key": "energy_import_today",
        "register": 4915,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "swap": True,
        "fast": False,
    },
    {
        "name": "37. Energy Export Lifetime",
        "key": "energy_export_lifetime",
        "register": 4872,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": False,
        "fast": False,
    },
    {
        "name": "36. Energy Export Today",
        "key": "energy_export_today",
        "register": 4917,
        "data_type": "uint32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
        "swap": True,
        "fast": False,
    },
    {
        "name": "39. Load Voltage",
        "key": "load_voltage",
        "register": 4900,
        "data_type": "uint16",
        "scale": 0.1,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "40. Load Current",
        "key": "load_current",
        "register": 4904,
        "data_type": "int32",
        "scale": 0.01,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": True,
        "fast": False,
    },
    {
        "name": "42. Light Load Lifetime Energy",
        "key": "light_load_lifetime_energy",
        "register": 4962,
        "data_type": "int32",
        "scale": 0.01,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
        "swap": False,
        "fast": False,
    },
    {
        "name": "31. Grid Export Power",
        "key": "grid_export_power",
        "register": 4099,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "46. Inverter Solar Conversion Power",
        "key": "inverter_solar_conversion_power",
        "register": 4151,
        "data_type": "int32",
        "scale": 0.1,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "swap": False,
        "fast": False,
    },
    {
        "name": "01. Inverter Operation Mode",
        "key": "inverter_operation_mode_raw",
        "register": 8448,
        "data_type": "uint16",
        "scale": 1,
        "unit": None,
        "device_class": None,
        "state_class": None,
        "swap": False,
        "fast": False,
    },
]

# ── Writable number entities ──────────────────────────────────────────────────
# (key, name, register, data_type, min, max, step, unit, mode)
NUMBER_DEFINITIONS = [
    {
        "key": "battery_charging_max_power",        # matches sensor key
        "name": "03. Battery Charging Max Power",
        "register": 8472,
        "data_type": "uint16",
        "min": 100,
        "max": 10000,
        "step": 50,
        "unit": "W",
    },
    {
        "key": "maximum_grid_charging_power",        # matches sensor key
        "name": "05. Max Grid Charging Power",
        "register": 8470,
        "data_type": "uint16",
        "min": 100,
        "max": 10000,
        "step": 50,
        "unit": "W",
    },
    {
        "key": "stop_grid_charging_battery_soc",     # matches sensor key
        "name": "06. Stop Grid Charging Battery SOC",
        "register": 8471,
        "data_type": "uint16",
        "min": 10,
        "max": 100,
        "step": 5,
        "unit": "%",
    },
    {
        "key": "battery_stop_charging_maximum_soc",  # matches sensor key
        "name": "04. Battery Stop Charging Maximum SOC",
        "register": 8473,
        "data_type": "uint16",
        "min": 80,
        "max": 100,
        "step": 5,
        "unit": "%",
    },
    {
        "key": "discharge_end_soc_on_grid",          # matches sensor key
        "name": "07. Discharge End SOC (on grid)",
        "register": 8522,
        "data_type": "uint16",
        "min": 10,
        "max": 95,
        "step": 5,
        "unit": "%",
    },
    {
        "key": "discharge_end_soc_on_battery",       # matches sensor key
        "name": "08. Discharge End SOC (on battery)",
        "register": 8475,
        "data_type": "uint16",
        "min": 5,
        "max": 20,
        "step": 1,
        "unit": "%",
    },
    {
        "key": "max_grid_export_power",              # matches sensor key
        "name": "02. Max Grid Export Power",
        "register": 12473,
        "data_type": "uint32",
        "min": 100,
        "max": 10000,
        "step": 100,
        "unit": "W",
    },
    {
        "key": "smart_load_turn_on_battery_soc",     # matches sensor key
        "name": "09. Smart Load Turn ON Battery SOC",
        "register": 8492,
        "data_type": "uint16",
        "min": 25,
        "max": 100,
        "step": 5,
        "unit": "%",
    },
    {
        "key": "smart_load_turn_off_battery_soc",    # matches sensor key
        "name": "10. Smart Load Turn OFF Battery SOC",
        "register": 8493,
        "data_type": "uint16",
        "min": 15,
        "max": 80,
        "step": 5,
        "unit": "%",
    },
]

OPERATION_MODE_OPTIONS = {
    "Self Used Mode": 0,
    "Feed-in Priority Mode": 1,
    "Time-based Control": 2,
    "Back-up Mode": 3,
}
OPERATION_MODE_REGISTER = 8448
